from django.conf.urls import url
from . import views

app_name = 'cars'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_register/$', views.user_register, name='user_register'),
    url(r'^long/$', views.long, name='long'),
    url(r'^short/$', views.short, name='short'),
    url(r'^shangwu/$', views.shangwu, name='shangwu'),
    url(r'^hunqing/$', views.hunqing, name='hunqing'),
    url(r'^daba/$', views.daba, name='daba'),
    url(r'^about/$', views.about, name='about'),
    url(r'^guide/$', views.guide, name='guide'),
    url(r'^order/(\d+)/$', views.order, name='order'),
    url(r'^commit/(\d+)/$', views.commit, name='commit'),
    url(r'^log_out/$', views.log_out, name='log_out'),
    url(r'^userinfo/$', views.userinfo, name='userinfo'),
    url(r'^pay/(\d+)/$', views.pay, name='pay'),
    url(r'^service/$', views.service, name='service'),
    url(r'^online/$', views.online, name='online'),
    url(r'^me/$', views.me, name='me'),
    url(r'^dingdan/$', views.dingdan, name='dingdan'),
    url(r'^xiugai/$', views.xiugai, name='xiugai'),
    url(r'^new/$', views.new, name='new'),
    url(r'^advice/$', views.advice, name='advice'),
    url(r'^success/$', views.success, name='success'),
    url(r'^header/$', views.header, name='header'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^changes/$', views.changes, name='changes'),
    url(r'^email/$', views.email, name='email'),
    url(r'^active/(.*?)/$', views.active, name='active'),
    url(r'^verifycode/$', views.verifycode, name='verifycode'),
    url(r'^checkuser/$', views.checkuser, name='checkuser'),
    url(r'^checkuser1/$', views.checkuser1, name='checkuser1'),
    url(r'^checkuser2/$', views.checkuser2, name='checkuser2'),
    url(r'^checkuser3/$', views.checkuser3, name='checkuser3'),
    url(r'^ajaxload/$', views.ajaxload, name='ajaxload'),
    url(r'^ajax/$', views.ajax, name='ajax'),
    url(r'^dianji/$', views.dianji, name='dianji'),
    url(r'^checkreturn/(\d+)/$', views.checkreturn, name='checkreturn'),
    url(r'^motai/$', views.motai, name='motai'),
]
