# Generated by Django 2.2 on 2019-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='realname',
            field=models.CharField(default='待完善', max_length=50),
        ),
    ]
