# Generated by Django 2.2 on 2019-04-25 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_customer_realname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='realname',
        ),
    ]
