# Generated by Django 2.2 on 2019-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carnum',
            field=models.IntegerField(default=100),
        ),
    ]
