# Generated by Django 2.2 on 2019-04-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_hotpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(default='/static/images/touxiang.png', upload_to='picture'),
        ),
    ]
