# Generated by Django 2.2 on 2019-04-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_customer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='picture',
            field=models.ImageField(default='/picture/touxiang.png', upload_to='picture'),
        ),
    ]
