# Generated by Django 2.2 on 2019-05-01 04:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20190501_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
