# Generated by Django 2.2 on 2019-05-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20190501_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_return',
            field=models.BooleanField(choices=[('F', 'M'), ('M', 'F')], default=False),
        ),
    ]
