# Generated by Django 2.2 on 2019-05-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_order_is_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_return',
            field=models.BooleanField(choices=[('T', '已还车'), ('F', '租赁中')], default=False, verbose_name='F'),
        ),
    ]
