# Generated by Django 2.2 on 2019-05-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20190511_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_return',
            field=models.CharField(choices=[('T', '已还车'), ('F', '租赁中')], default='F', max_length=20),
        ),
    ]
