# Generated by Django 2.2 on 2019-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_auto_20190511_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='./static/media/')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LongOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('rent', models.CharField(choices=[('1', '1个月'), ('2', '2个月'), ('3', '3个月'), ('4', '6个月'), ('5', '1年'), ('6', '2年')], default='1', max_length=20)),
                ('gettime', models.DateTimeField()),
                ('cartype', models.CharField(max_length=50)),
            ],
        ),
    ]
