# Generated by Django 2.2 on 2019-05-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20190511_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longorder',
            name='cartype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.LongCar'),
        ),
    ]
